---Q1.Find total revenue generated by each customer.

SELECT 
      customer.customer_id, 
	  first_name, 
	  last_name, 
	  SUM(amount) AS total_revenue 
FROM customer
JOIN payment
    ON customer.customer_id = payment.customer_id
GROUP BY customer.customer_id, first_name, last_name;

----Q.2 Show top 10 customers by total spending.


SELECT 
      customer.customer_id, 
	  first_name, 
	  last_name, 
	  SUM(amount) AS total_spend 
FROM customer
JOIN payment 
    ON customer.customer_id = payment.customer_id
GROUP BY customer.customer_id, first_name, last_name
ORDER BY total_spend DESC
LIMIT 10;

-----Q.3 Find total movies in each category


SELECT 
      category.name, 
	  COUNT(film.title) AS movie_count 
FROM film
JOIN film_category
    ON film.film_id = film_category.film_id
JOIN category 
    ON film_category.category_id = category.category_id
GROUP BY category.name;



----Q4. Calculate average movie length by category.

SELECT 
      category.name AS category, 
	  ROUND (AVG(length), 2) AS avg_length 
FROM film
JOIN film_category 
    ON film.film_id = film_category.film_id
JOIN category 
    ON film_category.category_id = category.category_id
GROUP BY category.name;



----Q5. Find customers who rented more than 20 movies.



SELECT
      customer.customer_id, 
	  CONCAT (first_name, ' ', last_name) AS customer_name, 
	  COUNT(rental_id) AS total_rent 
FROM customer
JOIN rental 
     ON customer.customer_id = rental.customer_id
GROUP BY customer.customer_id, first_name, last_name
HAVING COUNT(rental_id) > 20


-----Q6. Show monthly revenue trend.

SELECT 
      EXTRACT(YEAR FROM payment_date) AS YEAR,
	  EXTRACT(MONTH FROM payment_date) AS MONTH,
	  SUM(amount) total_revenue
from payment
GROUP BY 
        EXTRACT(YEAR FROM payment_date),
	    EXTRACT(MONTH FROM payment_date)
ORDER BY YEAR ASC, MONTH ASC;


----Q7. Find total rentals for each movie.


SELECT 
      film.film_id,
	  film.title AS movie_title,
	  COUNT(rental.rental_id) AS total_rentals
FROM film
JOIN inventory  
    ON film.film_id = inventory.film_id
JOIN rental 
    ON inventory.inventory_id = rental.inventory_id
GROUP BY film.film_id,
	     film.title
ORDER BY total_rentals DESC;


----Q8. Find movies that were never rented.

SELECT 
      film.film_id AS movie_id, 
	  film.title 
FROM film
LEFT JOIN inventory 
         ON film.film_id = inventory.film_id
LEFT JOIN rental 
         ON inventory.inventory_id = rental.inventory_id
WHERE rental.rental_id IS NULL;


----Q9. Find top 5 categories generating highest revenue.

SELECT 
      category.name,
	  SUM(payment.amount) AS total_revenue
FROM category
JOIN film_category 
    ON category.category_id = film_category.category_id
JOIN film
    ON film_category.film_id = film.film_id
JOIN inventory
    ON film.film_id = inventory.film_id
JOIN rental
    ON inventory.inventory_id = rental.inventory_id
JOIN payment 
    ON rental.rental_id = payment.rental_id
GROUP BY category.name
ORDER BY total_revenue DESC
LIMIT 5;



----Q10.Calculate the total revenue generated by each store.

SELECT 
      store.store_id,
	  CONCAT (staff.first_name, ' ', staff.last_name) AS manager_name,
	  SUM(payment.amount) AS total_revenue
FROM store
JOIN staff 
    ON store.store_id = staff.store_id
JOIN payment
    ON staff.staff_id = payment.staff_id
GROUP BY store.store_id,
	    CONCAT (staff.first_name, ' ', staff.last_name)
ORDER BY total_revenue DESC;



























